version: '3.6'
services:
webapp:
  container_name: 'wax-webapp-boilerplate'
  build:
    context: ./
    dockerfile: Dockerfile
  ports:
    - '80:80'
  environment:
    REACT_APP_TAG: '${REACT_APP_TAG}'
    REACT_APP_TITLE: '${REACT_APP_TITLE}'
    REACT_APP_LOGO: '${REACT_APP_LOGO}'
    REACT_APP_FOOTER_LINKS: '${REACT_APP_FOOTER_LINKS}'
    REACT_APP_WAX_APP_NAME: '${REACT_APP_WAX_APP_NAME}'
    REACT_APP_WAX_API_PROTOCOL: '${REACT_APP_WAX_API_PROTOCOL}'
    REACT_APP_WAX_API_HOST: '${REACT_APP_WAX_API_HOST}'
    REACT_APP_WAX_API_PORT: '${REACT_APP_WAX_API_PORT}'
    REACT_APP_WAX_CHAIN_ID: '${REACT_APP_WAX_CHAIN_ID}'
    REACT_APP_HASURA_URL: '${REACT_APP_HASURA_URL}'
  restart: on-failure
  volumes:
    - ./build:/usr/share/nginx/html
